#!/usr/bin/ruby

require 'fileutils'
require 'mysql'
require File.dirname(__FILE__) + '/graderutils.rb'

__TEST__ = true

def get_name(problem, dir)
	return problem if !FileTest.exist?("#{dir}/#{problem}")
	ex = 2
	while FileTest.exist?("#{dir}/#{problem}_#{ex}")
		ex += 1
	end
	return "#{problem}_#{ex}"
end

########################################################################

cafeprompt_dir, path_config = GraderUtils.initial(__FILE__)
cafe_dir = path_config['cafegrader:']
problems = Dir[cafeprompt_dir + '/problemset/*']
FileUtils.cd(cafe_dir + '/judge')
sql = GraderSql.new(cafe_dir)
problems.each do |s|
	problem = File.basename(s)
	p_new = get_name(problem, cafe_dir + '/judge/ev')
	id = sql.insert(p_new)
	FileUtils.mkdir_p("#{cafe_dir}/web/data/tasks/#{id}")
	FileUtils.cp("#{s}/#{problem}.pdf", \
"#{cafe_dir}/web/data/tasks/#{id}/#{p_new}.pdf")
	`#{cafe_dir}/judge/scripts/import_problem #{p_new} #{s} \
text -t 1 -m 32`
	if __TEST__
		FileUtils.mkdir_p(cafeprompt_dir + "/backup")
		FileUtils.cp_r(s, cafeprompt_dir + "/backup/#{p_new}")
	end
	FileUtils.remove_dir(s)
end
sql.close
